services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Sao_Paulo
    volumes:
      - /docker/stack_data/heimdall/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - shared_network
      
networks:
  shared_network:
    external: true
