services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Madrid
    volumes:
      - config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - shared_network

volumes:
    config:
        driver: local
networks:
  shared_network:
    external: true
