services:
  heimdall:
    image: linuxserver/heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - heimdall_data/config:/config
    ports:
      - 80:80
      - 443:443
    networks:
      - shared_network
      
networks:
  shared_network:
    external: true
    driver_opts:
      com.docker.network.driver.overlay: "true"

volumes:
  heimdall_data:
