secrets:
  smtp_to_telegram_chat_id:
    external: true
  smtp_to_telegram_bot_token:
    external: true

services:
  smtp_to_telegram:
    image: smtp_to_telegram:arm64
    environment:
      - UID=1000
      - GID=1000
      - ST_TELEGRAM_CHAT_IDS_FILE=/run/secrets/smtp_to_telegram_chat_id
      - ST_TELEGRAM_BOT_TOKEN_FILE=/run/secrets/smtp_to_telegram_bot_token
      - TZ=America/Sao_Paulo
    secrets:
      - smtp_to_telegram_chat_id
      - smtp_to_telegram_bot_token
    ports:
      - "2525:2525/tcp"
    networks:
      - shared_network

networks:
  shared_network:
    external: true
    driver_opts:
      com.docker.network.driver.overlay: "true"
