secrets:
  smtp_to_telegram_chat_id:
    external: true
  smtp_to_telegram_bot_token:
    external: true


services:
  smtp_to_telegram:
    container_name: smtp_to_telegram
    image: smtp_to_telegram
    environment:
      - UID=0
      - GID=0
      - ST_TELEGRAM_CHAT_IDS=${SMTP_TO_TELEGRAM_CHAT_ID_CONTENT}
      - ST_TELEGRAM_BOT_TOKEN=${SMTP_TO_TELEGRAM_BOT_TOKEN_CONTENT}
      - TZ=America/Sao_Paulo
    secrets:
      - smtp_to_telegram_chat_id
      - smtp_to_telegram_bot_token
    ports:
      - "2525:2525/tcp"
    networks:
      - shared_network

networks:
  shared_network:
    external: true
    driver_opts:
      com.docker.network.driver.overlay: "true"
