services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - /opt/data/uptime-kuma/data:/app/data
    networks:
      - homelab_shared
    dns:
      - 192.168.10.1
networks:
  homelab_shared:
    external: true
