services:
  mongo:
    image: mongo:6
    container_name: your-spotify-mongo
    restart: unless-stopped
    volumes:
      - /opt/data/your-spotify/mongo:/data/db
    networks:
      - internal

  your_spotify:
    image: lscr.io/linuxserver/your_spotify:latest
    container_name: your-spotify
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8087:80"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
      APP_URL: "${APP_URL}"
      SPOTIFY_PUBLIC: "${SPOTIFY_PUBLIC}"
      SPOTIFY_SECRET: "${SPOTIFY_SECRET}"
      CORS: "https://spotify.vega.punklab.xyz"
      MONGO_ENDPOINT: "mongodb://mongo:27017/your_spotify"
    networks:
      - internal
      - homelab_shared
networks:
  internal:
    driver: bridge
  homelab_shared:
    external: true
